/**
 * Exercise image lookup using a pre-built static map from ExerciseDB.
 *
 * The map is generated by `scripts/buildGifMap.mjs` which fetches all 1500+
 * exercises from ExerciseDB and fuzzy-matches them to our seed exercises.
 *
 * GIF URLs are proxied through wsrv.nl because static.exercisedb.dev has
 * TLS certificate issues that cause React Native Image to fail.
 *
 * Run `node scripts/buildGifMap.mjs` to rebuild the map.
 */

import gifMap from '@/data/exerciseGifMap.json';

// In-memory cache: exercise name (lowercase) → proxied gifUrl | null
const cache = new Map<string, string | null>();

/**
 * Proxy ExerciseDB GIF URLs through wsrv.nl to avoid TLS errors.
 * wsrv.nl is a free, open-source image proxy with valid certificates.
 */
export function proxyUrl(url: string): string {
  if (url.includes('static.exercisedb.dev') && !url.startsWith('https://wsrv.nl/')) {
    // wsrv.nl proxies the image with valid TLS; n=-1 preserves GIF animation
    return `https://wsrv.nl/?url=${encodeURIComponent(url)}&n=-1`;
  }
  return url;
}

// Seed cache from the static map (with proxied URLs)
for (const [name, url] of Object.entries(gifMap)) {
  cache.set(name, proxyUrl(url as string));
}

/**
 * Normalize name for comparison: lowercase, trim, collapse spaces.
 */
function normalize(name: string): string {
  return name.toLowerCase().trim().replace(/\s+/g, ' ');
}

/**
 * Look up exercise GIF URL from the static map.
 * Returns the proxied GIF URL or null if no match found.
 */
export async function fetchExerciseGif(exerciseName: string): Promise<string | null> {
  const key = normalize(exerciseName);
  return cache.get(key) ?? null;
}

/**
 * Seed the cache with a known URL (e.g. loaded from SQLite).
 */
export function cacheExerciseGif(exerciseName: string, gifUrl: string) {
  cache.set(normalize(exerciseName), proxyUrl(gifUrl));
}
