/**
 * Exercise image lookup using a pre-built static map from ExerciseDB.
 *
 * The map is generated by `scripts/buildGifMap.mjs` which fetches all 1500+
 * exercises from ExerciseDB and fuzzy-matches them to our seed exercises.
 *
 * GIF URLs are proxied through wsrv.nl because static.exercisedb.dev has
 * TLS certificate issues that cause React Native Image to fail.
 *
 * Run `node scripts/buildGifMap.mjs` to rebuild the map.
 */

import gifMap from '@/data/exerciseGifMap.json';

// In-memory cache: exercise name (lowercase) → proxied gifUrl | null
const cache = new Map<string, string | null>();

/**
 * Proxy ExerciseDB GIF URLs through wsrv.nl to avoid TLS errors.
 * Unwraps any stale double-proxied URLs stored in SQLite from previous sessions.
 */
export function proxyUrl(url: string): string {
  // Unwrap any existing wsrv.nl proxy layers to get the raw URL
  let raw = url;
  while (raw.startsWith('https://wsrv.nl/?url=')) {
    const match = raw.match(/^https:\/\/wsrv\.nl\/\?url=([^&]+)/);
    if (!match) break;
    raw = decodeURIComponent(match[1]);
  }
  // Proxy the raw URL if it's from exercisedb
  if (raw.includes('static.exercisedb.dev')) {
    return `https://wsrv.nl/?url=${encodeURIComponent(raw)}&n=-1`;
  }
  return raw;
}

// Seed cache from the static map (with proxied URLs)
for (const [name, url] of Object.entries(gifMap)) {
  cache.set(name, proxyUrl(url as string));
}

/**
 * Normalize name for comparison: lowercase, trim, collapse spaces.
 */
function normalize(name: string): string {
  return name.toLowerCase().trim().replace(/\s+/g, ' ');
}

// Noise words to ignore during fuzzy matching
const NOISE = new Set([
  'the', 'a', 'an', 'with', 'and', 'for', 'on', 'to', 'of', 'in', 'at', 'by',
]);

/**
 * Extract significant words (>2 chars, not noise) from a normalized name.
 */
function significantWords(name: string): string[] {
  return normalize(name)
    .replace(/[(),-]/g, ' ')
    .split(/\s+/)
    .filter(w => w.length > 2 && !NOISE.has(w));
}

// Pre-compute significant words for every map entry (once at startup)
const mapEntries: { name: string; words: string[]; url: string }[] = [];
for (const [name, url] of Object.entries(gifMap)) {
  mapEntries.push({ name, words: significantWords(name), url: url as string });
}

/**
 * Fuzzy-match an exercise name against the gif map using word overlap.
 * Returns the best match URL (proxied) or null if none is good enough.
 */
function fuzzyMatch(exerciseName: string): string | null {
  const words = significantWords(exerciseName);
  if (words.length < 2) return null; // Too few words to match reliably

  let bestUrl: string | null = null;
  let bestScore = 0;

  for (const entry of mapEntries) {
    const shared = words.filter(w => entry.words.includes(w)).length;
    if (shared < 2) continue; // Require at least 2 shared words
    const score = shared / Math.max(words.length, entry.words.length);
    if (score > bestScore) {
      bestScore = score;
      bestUrl = entry.url;
    }
  }

  // Require at least 50% overlap
  if (bestScore < 0.5) return null;
  return bestUrl ? proxyUrl(bestUrl) : null;
}

/**
 * Look up exercise GIF URL from the static map.
 * Falls back to fuzzy word-overlap matching if exact match fails.
 * Returns the proxied GIF URL or null if no match found.
 */
export async function fetchExerciseGif(exerciseName: string): Promise<string | null> {
  const key = normalize(exerciseName);

  // Check cache (includes exact matches and previous fuzzy results)
  if (cache.has(key)) return cache.get(key)!;

  // Fuzzy match fallback
  const fuzzyUrl = fuzzyMatch(exerciseName);
  cache.set(key, fuzzyUrl); // Cache even null to avoid re-scanning
  return fuzzyUrl;
}

/**
 * Seed the cache with a known URL (e.g. loaded from SQLite).
 */
export function cacheExerciseGif(exerciseName: string, gifUrl: string) {
  cache.set(normalize(exerciseName), proxyUrl(gifUrl));
}
